### ISSUE TITLE
Custom settings not saving

### ISSUE THREAD

**Issue by haihefa** [MicaForEveryone/MicaForEveryone#193]
**Describe the bug**

**To Reproduce**
1. Go to MicaForEveryone
2. Click on create custom rule, set a few.
3. Restart your pc
4. All the custom rules are set to default. Very annoying!

**Expected behavior**
It should actually save settings.

**Screenshots**
No screenshots, every single option is reset to default after restart.

**Windows Version**
Windows 11 22H2 22621.819

**Additional context**
It didn't happen before.

**Comment by xmine64** [comment]
In general tab you can select the file where your rules are saved in it. What is the file path?

**Comment by haihefa** [comment]
> 

Default path. However I found a workaround: set up everything as you'd like then set the file as read-only. It will, of course, no longer be reset.

**Comment by xmine64** [comment]
Weird, I'll look in to this. It checks if the file doesn't exist then copies the default config to that path, maybe it fails.

**Comment by haihefa** [comment]
Let me clarify, it's **not** that all settings are reset to default, what I mean is:
1. Custom rule list is not forgotten (let's say I've added regedit, notepad++, vlc)
2. What _is_ forgotten are custom settings **in** each custom rule
3. So for example I've set up vlc to use Dark and Acrylic - well, it'd show up as VLC (custom rule entry) but with all its parameters **Default**

**Comment by haihefa** [comment]
However, making the file read-only will prevent those _buggy_ changes.

**Comment by xmine64** [comment]
Thanks for reporting the bug, I just fixed it.

**Comment by Dhyfer1** [comment]
> Thanks for reporting the bug, I just fixed it.

@xmine64 I'm sorry, but the problem is still present and I have the same problem as the author of this issue. These are the steps I have done when adding the process of a custom X program.

1. I open MFE, click on **+Add Rule** > click on **Add Process Rule**
2. In the dialog box **Add Rule**, I type in the search field the name of the process X, then Enter
3. The new process X appears last in the MFE settings. Then, for this new process X I set the Corner Mode option to Rounded.
4. I verify that this MFE configuration has been applied to process X, and I see that it works.
5. Then in MFE I go to **General** > **Config** File > **Edit in Text Editor** and when I open the file with Notepad, the process X appears as Default (Not rounded) in the line **CornerPreference**. 
6. Then I close MFE, thinking that maybe the change I have made in the Corner Mode option is applied in the configuration file after closing MFE, so I close MFE, then open MFE again, then check the configuration file again and it still appears as `CornerPreference = Default` for process X, but in MFE Corner Mode it still appears as Rounded.
7. I restart the PC, log in, open MFE and the settings I have applied in Corner Mode change to Default automatically.

So when a custom X process is added to MFE, the changes are reflected inside MFE, but not in the configuration file, and it only happens when a custom X process is added. But instead when I make some changes in the Explorer process, the changes are reflected in the configuration file and they are maintained after restarting/booting the PC.

Please fix this bug that is still present in MFE.

**Comment by Dhyfer1** [comment]
> > Thanks for reporting the bug, I just fixed it.
> 
> @xmine64 I'm sorry, but the problem is still present and I have the same problem as the author of this issue. These are the steps I have done when adding the process of a custom X program.
> 
> 1. I open MFE, click on **+Add Rule** > click on **Add Process Rule**
> 2. In the dialog box **Add Rule**, I type in the search field the name of the process X, then Enter
> 3. The new process X appears last in the MFE settings. Then, for this new process X I set the Corner Mode option to Rounded (appears as Default before any changes)
> 4. I verify that this MFE configuration has been applied to process X, and I see that it works.
> 5. Then in MFE I go to **General** > **Config File** > **Edit in Text Editor** and when I open the file with Notepad, the process X appears as Default (Not Rounded) in the line **CornerPreference**.
> 6. Then I close MFE, thinking that maybe the change I have made in the Corner Mode option is applied in the configuration file after closing MFE, so I close MFE, then open MFE again, then check the configuration file again and it still appears as `CornerPreference = Default` for process X, but in MFE Corner Mode it still appears as Rounded.
> 7. I restart the PC, log in, open MFE and the settings I have applied in Corner Mode for process X change to Default automatically.
> 
> So when a custom X process is added to MFE, the changes are reflected inside MFE, but not in the configuration file, and it only happens when a custom X process is added. But instead when I make some changes in the Explorer process, the changes are reflected in the configuration file and they are maintained after restarting/booting the PC.
> 
> Please fix this bug that is still present in MFE.
> 
> Edit: As mentioned by @haihefa in [#193 (comment)](https://github.com/MicaForEveryone/MicaForEveryone/issues/193#issuecomment-1336511495) his workaround was to set the file to read-only, in my case for process X my workaround was to manually edit the configuration file replacing `CornerPreference = Default` to `CornerPreference = Rounded` and that change worked for me, it even held after restarting/booting the PC. I didn't need to use the workaround made by @haihefa
